# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5df0ec0b8e6b78d56209a0de3e17456ed605c88649a4dac919688d9e0904d08e737d78decd8c4244e68a0fcbe52b54fc82a73e7e6f3b3bb09c98b40a435867cd

test:
  secret_key_base: 2f47426fa211ea697e2995c32f8e7f43fad7d4801c1bdd0e54702b3394c61da1229905739f88e5b4fbf67370fcfc89d47132616a50f2dbe65811e1f1a93dee16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
